In [1]:
import pandas as pd
import numpy as np
import re

In [4]:
df = pd.read_csv('CAM_TEST_DATA.csv')
df.head()

,Timestamp,accepted_ict,address,year_of_birth,cam_teams,type_of_structural_driver,education_level,No_of_child_enumerated,med_history_comements,linked,...,recency_status,med_history_comements.1,phone,last_test,income_level,Unnamed: 25,No_of_child_enumerated.1,recency_status.1,address.1,med_history_comements.2
0,117111572,No,Ikiang Bakasi,2020,Akpabuyo 1,Health-Center,Secondary,2,dhd,No,...,jdjdj,ggs,nnsn,<1 month,3,Long-Term Infection,2,Recent Infection,yyye,bdbbd
1,117176472,No,Mbarakom,1977,Odukpani 1,Others,Secondary,3,dhd,Yes,...,NaN,ggs,nnsn,> 6 months,3,Not Done,7,Long-Term Infection,yyye,bdbbd
2,116807526,No,Old Netim Road Okomita,1950,Calabar South,Health-Center,Post-Graduate,3,dhd,Yes,...,NaN,ggs,nnsn,4-6 months,3,NaN,1,Not Done,yyye,bdbbd
3,116720569,No,Old Road Okomita,1956,Obubra,Plantation,Not Educated,3,dhd,No,...,jdjdj,ggs,nnsn,4-6 months,2,NaN,4,Recent Infection,yyye,bdbbd
4,121219384,Yes,Opp Club 19......isonginyang Akamkpa,2001,Boki,Prayer House,Primary,1,dhd,No,...,jdjdj,ggs,nnsn,> 6 months,2,NaN,3,Long-Term Infection,yyye,bdbbd

In [7]:
df['Age']= 2022 - df.year_of_birth 
df.head()

,Timestamp,accepted_ict,address,year_of_birth,cam_teams,type_of_structural_driver,education_level,No_of_child_enumerated,med_history_comements,linked,...,med_history_comements.1,phone,last_test,income_level,Unnamed: 25,No_of_child_enumerated.1,recency_status.1,address.1,med_history_comements.2,Age
0,117111572,No,Ikiang Bakasi,2020,Akpabuyo 1,Health-Center,Secondary,2,dhd,No,...,ggs,nnsn,<1 month,3,Long-Term Infection,2,Recent Infection,yyye,bdbbd,2
1,117176472,No,Mbarakom,1977,Odukpani 1,Others,Secondary,3,dhd,Yes,...,ggs,nnsn,> 6 months,3,Not Done,7,Long-Term Infection,yyye,bdbbd,45
2,116807526,No,Old Netim Road Okomita,1950,Calabar South,Health-Center,Post-Graduate,3,dhd,Yes,...,ggs,nnsn,4-6 months,3,NaN,1,Not Done,yyye,bdbbd,72
3,116720569,No,Old Road Okomita,1956,Obubra,Plantation,Not Educated,3,dhd,No,...,ggs,nnsn,4-6 months,2,NaN,4,Recent Infection,yyye,bdbbd,66
4,121219384,Yes,Opp Club 19......isonginyang Akamkpa,2001,Boki,Prayer House,Primary,1,dhd,No,...,ggs,nnsn,> 6 months,2,NaN,3,Long-Term Infection,yyye,bdbbd,21

In [7]:
import socket
hostname = socket.gethostname()
print(socket.gethostbyname(hostname))

172.29.48.1
HYBORN

In [ ]:
def visitor_ip_address(request):
    x_forwarded_for = request.META.get('HTTP_X_FORWARDED_FOR')
    if x_forwarded_for:
        ip = x_forwarded_for.split(',')[0]
    else:
        ip = request.META.get('REMOTE_ADDR')
    return ip

In [9]:
import socket
def get_ip():
        s = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
        s.settimeout(0)
        try:
            # doesn't even have to be reachable
            s.connect(('10.254.254.254', 1))
            IP = s.getsockname()[0]
        except Exception:
            IP = '127.0.0.1'
        finally:
            s.close()
        return IP
print(get_ip())

192.168.43.229

In [72]:
import re
match = re.match(r'([0-9.-]+).+?([0-9.-]+)', '14.344')
lat = float(match.group(1))
longi = float(match.group(2))

print(longi)

4.0

In [4]:
lister = range(2022, 1940,1)
print(lister)

range(2022, 1940)

In [15]:

print(news.insert(0,"-"))

None

In [10]:
text='---'
def check(word):
    list ='!@#$%^&*()-+?_=,<>/'
    if (word.strip() == '' or  word in list or word == '---'):
        return True   
print(check(text))

None

In [46]:
text='-'
def check(word):
    list ='!@#$%^&*()-+?_=,<>/'
    if word in list:
        return True

print(check(text))

True

In [24]:
import re
def is_empty_or_blank(msg):
    """ This function checks if given string is empty
     or contain only shite spaces"""
    if re.search("^\s*$", msg):
        return True

hh =''
print(is_empty_or_blank(hh))

True

In [3]:

from geolocation.main import GoogleMaps

address = 'New York City Wall Street 12'

google_maps = GoogleMaps(api_key='AIzaSyCDt68QQvfU5KqGPWuXMDLn5fERcVs84x8')

location = google_maps.search(location=address) # sends search to Google Maps.

print(location.all()) # returns all locations.

my_location = location.first() # returns only first location.

print(my_location.city)
print(my_location.route)
print(my_location.street_number)
print(my_location.postal_code)

# for administrative_area in my_location.administrative_area:
# print(“{}: {} ({})”.format(administrative_area.area_type,
# administrative_area.name, administrative_area.short_name))

print(my_location.country)
print(my_location.country_shortcut)

print(my_location.formatted_address)

print(my_location.lat)
print(my_location.lng)

ModuleNotFoundError: No module named 'geolocation'

In [4]:
import json
import urllib2

def location_lookup():
  try:
    return json.load(urllib2.urlopen('http://ipinfo.io/json'))
  except urllib2.HTTPError:
    return False

location = location_lookup()

# print city and latitude/longitude
print (location['city'] + ' (' + location['loc'] + ')')

ModuleNotFoundError: No module named 'urllib2'

In [22]:

from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from webdriver_manager.chrome import ChromeDriverManager
from selenium.webdriver.common.by import By
import json
import time

s = Service(ChromeDriverManager().install())
driver = webdriver.Chrome(service=s)
driver.get('https://www.google.com')

string = '''
   function getLocation(callback) {
        if (navigator.geolocation) {
            navigator.geolocation.getCurrentPosition(function(position) {
                var myjson = {"latitude":position.coords.latitude, "longitude":position.coords.longitude};
                console.log(position);
                console.log(position.coords.latitude);
                console.log(position.coords.longitude); 
                var stringJson = JSON.stringify(myjson);
                callback(stringJson);
            });
        } else {
            console.log("Geolocation is not supported by this browser.");
        }
    }
    
    getLocation(function(callback) {
        console.log(callback);
        const para = document.createElement("p");
        para.innerHTML = callback;
        para.id = "location";
        document.body.appendChild(para);
    });'''.replace('\n', '').replace('\t', '')


# repeat this code
driver.execute_script(string)
time.sleep(2)
res = driver.find_element(By.ID, "location")
loc = res.text
locDict = json.loads(loc)
print("latitude: %f, longitude: %f" % (locDict["latitude"], locDict["longitude"]))

ModuleNotFoundError: No module named 'webdriver_manager'

In [21]:

from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from webdriver_manager.chrome import ChromeDriverManager
from selenium.webdriver.common.by import By
import json
import time

s = Service(ChromeDriverManager().install())
driver = webdriver.Chrome(service=s)
driver.get('https://www.google.com')

string = '''
   function getLocation(callback) {
        if (navigator.geolocation) {
            navigator.geolocation.getCurrentPosition(function(position) {
                var myjson = {"latitude":position.coords.latitude, "longitude":position.coords.longitude};
                console.log(position);
                console.log(position.coords.latitude);
                console.log(position.coords.longitude); 
                var stringJson = JSON.stringify(myjson);
                callback(stringJson);
            });
        } else {
            console.log("Geolocation is not supported by this browser.");
        }
    }
    
    getLocation(function(callback) {
        console.log(callback);
        const para = document.createElement("p");
        para.innerHTML = callback;
        para.id = "location";
        document.body.appendChild(para);
    });'''.replace('\n', '').replace('\t', '')


# repeat this code
driver.execute_script(string)
time.sleep(2)
res = driver.find_element(By.ID, "location")
loc = res.text
locDict = json.loads(loc)
print("latitude: %f, longitude: %f" % (locDict["latitude"], locDict["longitude"]))

Latitude: 4.7774
Longitude: 7.0134

In [5]:
mytoken ='175326d4db4e2d'
# https://ipinfo.io/json?token=mytoken
import requests

response = requests.get('https://ipinfo.io/json?token=175326d4db4e2d').json()

print(response)

{'ip': '102.89.40.120', 'city': 'Lalupon', 'region': 'Oyo', 'country': 'NG', 'loc': '7.4679,4.0659', 'org': 'AS29465 MTN NIGERIA Communication limited', 'timezone': 'Africa/Lagos'}

In [23]:
from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from webdriver_manager.chrome import ChromeDriverManager
from selenium.webdriver.common.by import By
import json
import time
url ="'https://www.google.com'"
driver = webdriver.Chrome(executable_path='C:\Windows\chromedriver.exe')
driver.maximize_window()
driver.get(url)
# time.sleep(50)


string = '''
   function getLocation(callback) {
        if (navigator.geolocation) {
            navigator.geolocation.getCurrentPosition(function(position) {
                var myjson = {"latitude":position.coords.latitude, "longitude":position.coords.longitude};
                console.log(position);
                console.log(position.coords.latitude);
                console.log(position.coords.longitude); 
                var stringJson = JSON.stringify(myjson);
                callback(stringJson);
            });
        } else {
            console.log("Geolocation is not supported by this browser.");
        }
    }
    
    getLocation(function(callback) {
        console.log(callback);
        const para = document.createElement("p");
        para.innerHTML = callback;
        para.id = "location";
        document.body.appendChild(para);
    });'''.replace('\n', '').replace('\t', '')


# repeat this code
driver.execute_script(string)
time.sleep(2)
res = driver.find_element(By.ID, "location")
loc = res.text
locDict = json.loads(loc)
print("latitude: %f, longitude: %f" % (locDict["latitude"], locDict["longitude"]))

ModuleNotFoundError: No module named 'webdriver_manager'

In [ ]:
print("Latitude = ", getLoc.latitude, "\n")
print("Longitude = ", getLoc.longitude)

NameError: name 'getLoc' is not defined

In [ ]:
df =pd.read_csv("CAM_TEST_DATA.csv")

In [ ]:
df.head()

,Timestamp,accepted_ict,address,DOB,cam_teams,has_children,client_code,structural_driver,education_level,No_of_child_enumerated,...,occupation,recency_test,recency_status,residence_LGA,residence_State,sex,test_result,income_level,lat,lon
0,2022-09-01,No,Ikiang Bakasi,1975-01-01,Akpabuyo 1,Yes,No,Health-Center,Secondary,2,...,hshsh,Yes,Long-Term Infection,SHSH,NSNS,Male,Positive,"#30,000- #100,000",4.9500,8.3250
1,2022-08-30,No,Mbarakom,1958-03-27,Odukpani 1,No,No,Others,Secondary,3,...,hshsh,No,Recent Infection,SHSH,NSNS,Male,Positive,"#100,000- #500,000",5.8915,8.0219
2,2022-08-31,No,Old Netim Road Okomita,1992-07-22,Calabar South,Yes,No,Health-Center,Post-Graduate,3,...,hshsh,Yes,Recent Infection,SHSH,NSNS,Female,Positive,"#30,000- #100,000",6.6682,9.1645
3,2022-09-04,No,Old Road Okomita,1973-05-12,Obubra,Yes,No,Plantation,Not Educated,3,...,hshsh,Yes,Recent Infection,SHSH,NSNS,Male,Negative,"less than #30,000",4.8843,8.4838
4,2022-09-05,Yes,Opp Club 19......isonginyang Akamkpa,1982-11-22,Boki,No,Yes,Prayer House,Primary,1,...,hshsh,Yes,Long-Term Infection,SHSH,NSNS,Female,Negative,#5000 and above,6.6913,8.9434

In [ ]:
# df.drop(df.iloc[:, 19:], inplace=True, axis=1)

In [ ]:
df.head()

,Timestamp,accepted_ict,address,DOB,cam_teams,has_children,client_code,structural_driver,education_level,No_of_child_enumerated,...,occupation,recency_test,recency_status,residence_LGA,residence_State,sex,test_result,income_level,lat,lon
0,2022-09-01,No,Ikiang Bakasi,1975-01-01,Akpabuyo 1,Yes,No,Health-Center,Secondary,2,...,hshsh,Yes,Long-Term Infection,SHSH,NSNS,Male,Positive,"#30,000- #100,000",4.9500,8.3250
1,2022-08-30,No,Mbarakom,1958-03-27,Odukpani 1,No,No,Others,Secondary,3,...,hshsh,No,Recent Infection,SHSH,NSNS,Male,Positive,"#100,000- #500,000",5.8915,8.0219
2,2022-08-31,No,Old Netim Road Okomita,1992-07-22,Calabar South,Yes,No,Health-Center,Post-Graduate,3,...,hshsh,Yes,Recent Infection,SHSH,NSNS,Female,Positive,"#30,000- #100,000",6.6682,9.1645
3,2022-09-04,No,Old Road Okomita,1973-05-12,Obubra,Yes,No,Plantation,Not Educated,3,...,hshsh,Yes,Recent Infection,SHSH,NSNS,Male,Negative,"less than #30,000",4.8843,8.4838
4,2022-09-05,Yes,Opp Club 19......isonginyang Akamkpa,1982-11-22,Boki,No,Yes,Prayer House,Primary,1,...,hshsh,Yes,Long-Term Infection,SHSH,NSNS,Female,Negative,#5000 and above,6.6913,8.9434

In [ ]:
df['DOB']= pd.to_datetime(df['DOB'])

In [ ]:
df['tested'] =1

In [ ]:
df.head()

,Timestamp,accepted_ict,address,DOB,cam_teams,has_children,client_code,structural_driver,education_level,No_of_child_enumerated,...,recency_test,recency_status,residence_LGA,residence_State,sex,test_result,income_level,lat,lon,tested
0,2022-09-01,No,Ikiang Bakasi,1975-01-01,Akpabuyo 1,Yes,No,Health-Center,Secondary,2,...,Yes,Long-Term Infection,SHSH,NSNS,Male,Positive,"#30,000- #100,000",4.9500,8.3250,1
1,2022-08-30,No,Mbarakom,1958-03-27,Odukpani 1,No,No,Others,Secondary,3,...,No,Recent Infection,SHSH,NSNS,Male,Positive,"#100,000- #500,000",5.8915,8.0219,1
2,2022-08-31,No,Old Netim Road Okomita,1992-07-22,Calabar South,Yes,No,Health-Center,Post-Graduate,3,...,Yes,Recent Infection,SHSH,NSNS,Female,Positive,"#30,000- #100,000",6.6682,9.1645,1
3,2022-09-04,No,Old Road Okomita,1973-05-12,Obubra,Yes,No,Plantation,Not Educated,3,...,Yes,Recent Infection,SHSH,NSNS,Male,Negative,"less than #30,000",4.8843,8.4838,1
4,2022-09-05,Yes,Opp Club 19......isonginyang Akamkpa,1982-11-22,Boki,No,Yes,Prayer House,Primary,1,...,Yes,Long-Term Infection,SHSH,NSNS,Female,Negative,#5000 and above,6.6913,8.9434,1

In [ ]:
def cardinality():
    yield_df = df.pivot_table(
        index='education_level', columns=['sex'], values='tested', aggfunc='sum').reset_index()
    # yield_df['total'] = yield_df['Negative'] + yield_df['Positive']
    return yield_df
cardinality()

sex education_level  Female  Male
0      Not Educated       5     6
1     Post-Graduate       4     6
2           Primary       6     1
3         Secondary       6     5
4          Tertiary       5     5

In [ ]:
dfn =df.pivot_table(index='sex', columns=['test_result'],values='tested', aggfunc='sum').reset_index()

dfn.head()

test_result     sex  Negative  Positive
0            Female        14        12
1              Male         8        15

In [ ]:
lonedf =df.groupby(['lat','lon','test_result']).size().reset_index().rename(columns={0:'total'})
lonedf.head()

       lat       lon test_result  total
0  4.10605  9.378958    Negative      1
1  4.19913  8.717560    Positive      1
2  4.28555  9.245874    Negative      1
3  4.28598  8.715700    Positive      1
4  4.28669  8.327940    Negative      1

In [ ]:
lonedf =df.groupby(['cam_teams','recency_status']).size().reset_index().rename(columns={0:'total'})
# lonedf = lonedf[(lonedf['test_result'] == 'Positive')& (df['recency_test'] == 'Yes')]
lonedf.head()

    cam_teams       recency_status  total
0   Abi-biase  Long-Term Infection      2
1   Abi-biase     Recent Infection      3
2   Akamkpa 1  Long-Term Infection      3
3   Akamkpa 1     Recent Infection      4
4  Akpabuyo 1  Long-Term Infection      2

In [ ]:
import plotly.express as px
import plotly.graph_objects as go
recency_fig = px.bar(lonedf, x='cam_teams', y='total',
                             hover_data=['cam_teams', 'total', 'recency_status'], color='recency_status',
                             labels={'rec': 'recency_status'}, height=400)
recency_fig.show()

In [ ]:
dfn =df.pivot_table(index=['lat','lon'], columns=['test_result'],values='tested', aggfunc='sum').reset_index()

dfn.head()

test_result      lat       lon  Negative  Positive
0            4.10605  9.378958       1.0       NaN
1            4.19913  8.717560       NaN       1.0
2            4.28555  9.245874       1.0       NaN
3            4.28598  8.715700       NaN       1.0
4            4.28669  8.327940       1.0       NaN

In [ ]:
profile_df =df.groupby(['test_result','sex','education_level','marital_status']).size().reset_index().rename(columns={0:'total'})
dfn =profile_df.pivot_table(index='education_level', columns=['test_result'],values='total', aggfunc='sum').reset_index()
dfn.head()

test_result education_level  Negative  Positive
0              Not Educated         7         4
1             Post-Graduate         3         7
2                   Primary         3         4
3                 Secondary         5         6
4                  Tertiary         4         6

In [ ]:
df['age'] =(pd.to_datetime('today').year-pd.to_datetime('DOB').year)

ParserError: Unknown string format: DOB

In [ ]:
df["age_group"] = pd.cut(x=df['age'], bins=[0,14,100], labels=["children","Adult"])
df

,Timestamp,accepted_ict,address,DOB,cam_teams,has_children,client_code,structural_driver,education_level,No_of_child_enumerated,...,recency_test,recency_status,residence_LGA,residence_State,sex,test_result,income_level,tested,age,age_group
0,2022-09-01,No,Ikiang Bakasi,1975-01-01,Akpabuyo 1,Yes,No,Health-Center,Secondary,2,...,Yes,Long-Term Infection,SHSH,NSNS,Male,Positive,"#30,000- #100,000",1,66,Adult
1,2022-08-30,No,Mbarakom,1958-03-27,Odukpani 1,No,No,Others,Secondary,3,...,No,Recent Infection,SHSH,NSNS,Male,Positive,"#100,000- #500,000",1,66,Adult
2,2022-08-31,No,Old Netim Road Okomita,1992-07-22,Calabar South,Yes,No,Health-Center,Post-Graduate,3,...,Yes,Recent Infection,SHSH,NSNS,Female,Positive,"#30,000- #100,000",1,66,Adult
3,2022-09-04,No,Old Road Okomita,1973-05-12,Obubra,Yes,No,Plantation,Not Educated,3,...,Yes,Recent Infection,SHSH,NSNS,Male,Negative,"less than #30,000",1,66,Adult
4,2022-09-05,Yes,Opp Club 19......isonginyang Akamkpa,1982-11-22,Boki,No,Yes,Prayer House,Primary,1,...,Yes,Long-Term Infection,SHSH,NSNS,Female,Negative,#5000 and above,1,66,Adult
5,2022-08-30,No,"Awi, Akamkpa",1988-07-17,Odukpani 2,No,No,Others,Not Educated,1,...,No,Recent Infection,SHSH,NSNS,Female,Negative,#5000 and above,1,66,Adult
6,2022-09-04,No,"Satilite Ttown, Calabar",1979-08-06,Odukpani 2,No,No,Health-Center,Not Educated,4,...,No,Long-Term Infection,SHSH,NSNS,Male,Positive,"#30,000- #100,000",1,66,Adult
7,2022-09-01,No,Oroks Compd Big Iwuru,1977-02-14,Odukpani 1,Yes,No,Traditional Bone-Setter,Post-Graduate,2,...,No,Recent Infection,SHSH,NSNS,Female,Negative,#5000 and above,1,66,Adult
8,2022-09-01,No,Odukpani Junction,1983-01-10,Boki,Yes,No,Health-Center,Not Educated,2,...,No,Long-Term Infection,SHSH,NSNS,Female,Negative,"less than #30,000",1,66,Adult
9,2022-08-30,No,Akamkpa,2008-02-14,Calabar Municipal 1,Yes,No,Health-Center,Secondary,1,...,Yes,Recent Infection,SHSH,NSNS,Female,Positive,"#30,000- #100,000",1,66,Adult
10,2022-09-04,No,No 5 Iyamba Street Akamkpa,1986-02-12,Yakurr,Yes,No,Health-Center,Post-Graduate,3,...,No,Long-Term Infection,SHSH,NSNS,Female,Positive,"less than #30,000",1,66,Adult
11,2022-09-05,Yes,133 Isong Inyang Str.,1985-05-24,Abi-biase,No,Yes,Settlement,Primary,1,...,Yes,Recent Infection,SHSH,NSNS,Female,Positive,"less than #30,000",1,66,Adult
12,2022-09-04,Yes,Behind Apostoplic Church Akampka,1980-04-01,Akamkpa 1,No,Yes,Health-Center,Secondary,4,...,No,Recent Infection,SHSH,NSNS,Male,Positive,"#30,000- #100,000",1,66,Adult
13,2022-08-30,Yes,Mr Owuna Compound Cal/ikomhighway,1982-07-27,Odukpani 1,Yes,Yes,Prayer House,Tertiary,4,...,Yes,Long-Term Infection,SHSH,NSNS,Female,Negative,"#30,000- #100,000",1,66,Adult
14,2022-08-29,Yes,Obung Akamkpa,1988-05-11,Akamkpa 1,No,Yes,Traditional Bone-Setter,Tertiary,1,...,No,Recent Infection,SHSH,NSNS,Female,Positive,"less than #30,000",1,66,Adult
15,2022-09-01,Yes,Ogoja Road Obudu Crs,1986-07-21,Obubra,No,Yes,Settlement,Post-Graduate,1,...,Yes,Recent Infection,SHSH,NSNS,Male,Positive,"less than #30,000",1,66,Adult
16,2022-09-02,No,Beside Civi Centre Uyanga Village Akamkpa,1958-06-18,Calabar Municipal 2,Yes,No,TBA,Tertiary,4,...,No,Recent Infection,SHSH,NSNS,Male,Positive,"#30,000- #100,000",1,66,Adult
17,2022-09-05,Yes,Gabriel Orgas Compound Nsan Akamkpa,1988-09-01,Akpabuyo 1,No,Yes,Others,Post-Graduate,2,...,Yes,Long-Term Infection,SHSH,NSNS,Male,Positive,#5000 and above,1,66,Adult
18,2022-09-04,Yes,3 Ikom Cal Road Akamkpa,1980-08-18,Boki,Yes,Yes,Settlement,Post-Graduate,4,...,No,Recent Infection,SHSH,NSNS,Male,Positive,#5000 and above,1,66,Adult
19,2022-09-02,No,Abakim Strret Uyanga,1990-10-15,Yakurr,Yes,No,Others,Tertiary,3,...,Yes,Recent Infection,SHSH,NSNS,Female,Negative,#5000 and above,1,66,Adult
20,2022-09-04,No,Clb 19 Along Base Camp Road Akampka,1961-10-16,Akamkpa 1,Yes,No,Prayer House,Post-Graduate,2,...,Yes,Long-Term Infection,SHSH,NSNS,Female,Negative,#5000 and above,1,66,Adult
21,2022-08-29,Yes,Opposite Court Uyanga,1970-10-15,Calabar Municipal 1,Yes,Yes,Plantation,Not Educated,3,...,Yes,Recent Infection,SHSH,NSNS,Male,Negative,#5000 and above,1,66,Adult
22,2022-09-04,Yes,I Man Village Akamkpa,1987-04-02,Ikom-Etung,No,Yes,Health-Center,Tertiary,2,...,Yes,Recent Infection,SHSH,NSNS,Male,Positive,"#30,000- #100,000",1,66,Adult
23,2022-09-03,Yes,Ntima Village Biase,2012-10-17,Yakurr,Yes,Yes,Prayer House,Secondary,2,...,No,Recent Infection,SHSH,NSNS,Female,Negative,"#100,000- #500,000",1,66,Adult
24,2022-08-30,Yes,Uyang,1991-10-21,Akpabuyo 1,Yes,Yes,TBA,Tertiary,1,...,No,Recent Infection,SHSH,NSNS,Male,Negative,#5000 and above,1,66,Adult
25,2022-09-01,Yes,Beb1 3 Oblk Crs,1943-04-13,Obubra,No,Yes,Prayer House,Secondary,4,...,No,Recent Infection,SHSH,NSNS,Male,Negative,"#30,000- #100,000",1,66,Adult
26,2022-08-30,No,19 Deeper Life Road Akamkpa,1986-12-05,Boki,Yes,No,Traditional Bone-Setter,Primary,3,...,Yes,Recent Infection,SHSH,NSNS,Female,Negative,"less than #30,000",1,66,Adult
27,2022-08-30,No,"Okpazan, Belegette",1970-07-12,Bakassi,No,No,Prayer House,Tertiary,1,...,No,Long-Term Infection,SHSH,NSNS,Female,Negative,"#30,000- #100,000",1,66,Adult
28,2022-09-04,No,Busi 1obanliku Crs,1964-06-17,Bakassi,Yes,No,PMV,Not Educated,1,...,Yes,Long-Term Infection,SHSH,NSNS,Male,Negative,#5000 and above,1,66,Adult
29,2022-08-29,No,Ojor Village,1978-09-14,Odukpani 1,No,No,Prayer House,Not Educated,3,...,No,Long-Term Infection,SHSH,NSNS,Female,Positive,"less than #30,000",1,66,Adult
30,2022-08-30,Yes,Busi 3 Village Oblk Crs,1985-04-24,Akamkpa 1,No,Yes,Health-Center,Post-Graduate,4,...,Yes,Long-Term Infection,SHSH,NSNS,Male,Negative,"#100,000- #500,000",1,66,Adult
31,2022-08-31,Yes,Obung Village,1963-04-09,Yakurr,No,Yes,PMV,Tertiary,3,...,No,Recent Infection,SHSH,NSNS,Male,Positive,#5000 and above,1,66,Adult
32,2022-08-29,No,Chief Alelele Comp. Sankwala,1969-02-08,Odukpani 2,No,No,Plantation,Post-Graduate,1,...,Yes,Recent Infection,SHSH,NSNS,Male,Positive,"#100,000- #500,000",1,66,Adult
33,2022-09-03,Yes,Ibiae Estate,1972-04-15,Akpabuyo 1,Yes,Yes,Healing home,Primary,3,...,No,Recent Infection,SHSH,NSNS,Female,Positive,"#30,000- #100,000",1,66,Adult
34,2022-09-01,Yes,Sam Umohnen Filling Station Akomita,1980-02-22,Akamkpa 1,No,Yes,Traditional Bone-Setter,Not Educated,4,...,No,Long-Term Infection,SHSH,NSNS,Male,Negative,"less than #30,000",1,66,Adult
35,2022-09-03,No,Lane B Edem Edet Calabar,1982-11-02,Odukpani 1,No,No,Traditional Bone-Setter,Secondary,3,...,Yes,Long-Term Infection,SHSH,NSNS,Female,Positive,"#100,000- #500,000",1,66,Adult
36,2022-09-01,Yes,Akwa Ibom,1977-11-10,Akpabuyo 2,No,Yes,PMV,Tertiary,2,...,Yes,Long-Term Infection,SHSH,NSNS,Male,Positive,"#30,000- #100,000",1,66,Adult
37,2022-09-02,No,Akamkpa,1980-01-10,Odukpani 2,Yes,No,PMV,Secondary,2,...,No,Long-Term Infection,SHSH,NSNS,Female,Negative,"less than #30,000",1,66,Adult
38,2022-08-30,No,California Street Old Netim,1972-10-06,Abi-biase,Yes,No,Plantation,Primary,2,...,Yes,Long-Term Infection,SHSH,NSNS,Male,Positive,"less than #30,000",1,66,Adult
39,2022-08-30,Yes,Opp Rose Agboche Compound Akamkpa,1973-11-15,Abi-biase,No,Yes,Health-Center,Tertiary,2,...,No,Long-Term Infection,SHSH,NSNS,Female,Positive,"#100,000- #500,000",1,66,Adult
40,2022-08-31,Yes,Mbarakom Road Akamkpa,1988-02-15,Abi-biase,Yes,Yes,Healing home,Primary,4,...,No,Recent Infection,SHSH,NSNS,Female,Positive,"less than #30,000",1,66,Adult
41,2022-09-05,Yes,52 Calabar/ikom Highway Akamkpa,1971-08-19,Akamkpa 1,No,Yes,Others,Secondary,2,...,No,Recent Infection,SHSH,NSNS,Female,Negative,#5000 and above,1,66,Adult
42,2022-09-01,Yes,Church Of Christ Ikot Effangha Calabar,1984-10-26,Akamkpa 1,Yes,Yes,PMV,Not Educated,1,...,Yes,Recent Infection,SHSH,NSNS,Female,Positive,"#100,000- #500,000",1,66,Adult
43,2022-09-01,Yes,Behind Apostolic Church Old Road Awi,1984-11-10,Abi-biase,No,Yes,PMV,Secondary,4,...,Yes,Recent Infection,SHSH,NSNS,Female,Positive,#5000 and above,1,66,Adult
44,2022-09-04,Yes,Ikpaicapit Ntanikpo Ugep,1977-05-30,Boki,Yes,Yes,Health-Center,Not Educated,3,...,No,Long-Term Infection,SHSH,NSNS,Male,Positive,"#100,000- #500,000",1,66,Adult
45,2022-09-05,Yes,Awi Road,1979-09-14,Akpabuyo 1,No,Yes,Health-Center,Secondary,4,...,Yes,Recent Infection,SHSH,NSNS,Male,Negative,"less than #30,000",1,66,Adult
46,2022-09-05,No,88 Cal/ikomhighway Akamkpa,1985-06-05,Obubra,No,No,PMV,Primary,1,...,No,Long-Term Infection,SHSH,NSNS,Female,Negative,"#30,000- #100,000",1,66,Adult
47,2022-08-29,No,"Mkpara 2 Ojor Village, Akamkpa",1983-04-21,Calabar Municipal 1,No,No,Health-Center,Post-Graduate,3,...,No,Recent Infection,SHSH,NSNS,Male,Positive,#5000 and above,1,66,Adult
48,2022-09-01,No,Okomita Village Akamkpa,1984-06-02,Bakassi,Yes,No,Settlement,Not Educated,4,...,No,Recent Infection,SHSH,NSNS,Female,Negative,"#30,000- #100,000",1,66,Adult

In [ ]:
def cardinality(one, two,three):
    yield_df = df.pivot_table(
        index=one, columns=[two], values=three, aggfunc='sum').reset_index()
    yield_df['total'] = yield_df['Negative'] + yield_df['Positive']
    return yield_df

cardinality('age_group','test_result','tested')

test_result age_group  Negative  Positive  total
0            children         1         1      2
1               Adult        21        26     47

In [ ]:
def cardinality(*columns):
  
    return df.groupby([*columns]).size().reset_index().rename(columns={0:'total'})

In [ ]:
# cardinality('Timestamp', 'test_result')
trend_df = cardinality('Timestamp', 'test_result').pivot_table(index='Timestamp', columns='test_result',
                                  values='total', aggfunc='sum').reset_index()
trend_df.head()

test_result   Timestamp  Negative  Positive
0            2022-08-29       1.0       4.0
1            2022-08-30       6.0       4.0
2            2022-08-31       NaN       3.0
3            2022-09-01       5.0       5.0
4            2022-09-02       2.0       1.0

In [ ]:
trend_df['new'] = pd.to_numeric(
        trend_df.Negative, errors='coerce').fillna(0)  + pd.to_numeric(
        trend_df.Positive, errors='coerce').fillna(0)
trend_df

test_result   Timestamp  Negative  Positive   new
0            2022-08-29       1.0       4.0   5.0
1            2022-08-30       6.0       4.0  10.0
2            2022-08-31       NaN       3.0   3.0
3            2022-09-01       5.0       5.0  10.0
4            2022-09-02       2.0       1.0   3.0
5            2022-09-03       1.0       2.0   3.0
6            2022-09-04       3.0       6.0   9.0
7            2022-09-05       4.0       2.0   6.0

In [ ]:
def cardinality(one, two, three, four):
    use_df = df.groupby([one, two, three, four]).size().reset_index().rename(columns={0:'total'})
    yield_df = use_df.pivot_table(index=one, columns=[four],values='total', aggfunc='sum').reset_index()
    yield_df['total'] = yield_df['Negative'] + yield_df['Positive']
    return yield_df

cardinality('sex','education_level', 'marital_status','test_result')

test_result     sex  Negative  Positive  total
0            Female        14        12     26
1              Male         8        15     23

In [ ]:
now = pd.to_datetime('now')
df['age'] =(now - df['DOB']).astype('<m8[Y]') 
df['age'](pd.to_datetime('today').year-pd.to_datetime('1956-07-01').year)

In [ ]:
df["age_group"] = pd.cut(x=df['age'], bins=[0,14,15], labels=["children","adults"])
df.head()

NameError: name 'df' is not defined

In [ ]:
df.to_clipboard()

NameError: name 'df' is not defined

In [ ]:
import plotly.graph_objects as go


def show_chart(df,labels):
    
        # Use `hole` to create a donut-like pie chart
    fig = go.Figure(
        data=[go.Pie(labels=df['marital_status'], values=df['total'], hole=.3)])
    fig.update_traces(textinfo='label+percent+value',
                                    hoverinfo='label+percent', textfont_size=15)
    fig.update_layout(margin=dict(l=0, r=0, t=40, b=0),
                                    paper_bgcolor='rgba(0,0,0,0)',
                                    plot_bgcolor='rgba(0,0,0,0)',
                                    font=dict(size=15),
                                    showlegend=False,
                                    title="HTS_TST |"+ {labels}
                                    )
    # st.plotly_chart(fig, use_container_width=True)
    fig.show()

show_chart(cardinality('marital_status','education_level', 'sex','test_result'),labels)

NameError: name 'labels' is not defined

In [ ]:
yield_df = df.pivot_table(index=['linked','Timestamp'], columns=['test_result'],values='te', aggfunc='sum').reset_index()
yield_df

KeyError: 'total'

In [ ]:
use_df =df[['Timestamp','linked','test_result']].groupby(['Timestamp', 'linked','test_result']).size().reset_index().rename(columns={0:'total'})
yield_df = use_df.pivot_table(index=['linked','Timestamp'], columns=['test_result'],values='total', aggfunc='sum').reset_index()
trand_df =yield_df[yield_df.columns[-3:]]
trand_df

test_result   Timestamp  Negative  Positive
0            2022-08-29       NaN       4.0
1            2022-08-30       2.0       2.0
2            2022-08-31       NaN       1.0
3            2022-09-01       2.0       2.0
4            2022-09-02       1.0       1.0
5            2022-09-03       NaN       2.0
6            2022-09-04       1.0       5.0
7            2022-09-05       1.0       1.0
8            2022-08-29       1.0       NaN
9            2022-08-30       4.0       2.0
10           2022-08-31       NaN       2.0
11           2022-09-01       3.0       3.0
12           2022-09-02       1.0       NaN
13           2022-09-03       1.0       NaN
14           2022-09-04       2.0       1.0
15           2022-09-05       3.0       1.0

In [ ]:
use_df =df[['Timestamp','linked','test_result']].groupby(['Timestamp', 'linked','test_result']).size().reset_index().rename(columns={0:'total'})
[use_df['test_result']=='Positive']
linked_df =use_df.pivot_table(index='Timestamp', columns=['linked'], values='total', aggfunc='sum').reset_index()

# trend_df['Positive'] =pd.to_numeric(trend_df.Positive, errors='coerce').fillna(0)
# trend_df['Negative'] =pd.to_numeric(trend_df.Positive, errors='coerce').fillna(0)
linked_df.head()

linked   Timestamp  No  Yes
0       2022-08-29   4    1
1       2022-08-30   4    6
2       2022-08-31   1    2
3       2022-09-01   4    6
4       2022-09-02   2    1

In [ ]:
trend_df =df.pivot_table(index='Timestamp', columns='test_result', values='tested', aggfunc='sum').reset_index()
trend_df['Positive'] =pd.to_numeric(trend_df.Positive, errors='coerce').fillna(0)
trend_df['Negative'] =pd.to_numeric(trend_df.Positive, errors='coerce').fillna(0)
trend_df.head()

test_result   Timestamp  Negative  Positive
0            2022-08-29       4.0       4.0
1            2022-08-30       4.0       4.0
2            2022-08-31       3.0       3.0
3            2022-09-01       5.0       5.0
4            2022-09-02       1.0       1.0

In [ ]:
trend_df = df.pivot_table(index='Timestamp', columns='test_result',
                              values='tested', aggfunc='sum').reset_index()

In [ ]:
filepath = "https://raw.githubusercontent.com/giswqs/leafmap/master/examples/data/us_cities.csv"
m = leafmap.Map(center=[40, -100], zoom=4, tiles="stamentoner")
m.add_heatmap(
    filepath,
    latitude="latitude",
    longitude="longitude",
    value="pop_max",
    name="Heat map",
    radius=20,
)

In [ ]:
new_df = df[['Timestamp','linked','test_result']].groupby(['Timestamp', 'linked','test_result']).size().reset_index().rename(columns={0:'total'})
new_df[new_df['test_result']=='Positive']

     Timestamp linked test_result  total
0   2022-08-29     No    Positive      4
3   2022-08-30     No    Positive      2
5   2022-08-30    Yes    Positive      2
6   2022-08-31     No    Positive      1
7   2022-08-31    Yes    Positive      2
9   2022-09-01     No    Positive      2
11  2022-09-01    Yes    Positive      3
13  2022-09-02     No    Positive      1
15  2022-09-03     No    Positive      2
18  2022-09-04     No    Positive      5
20  2022-09-04    Yes    Positive      1
22  2022-09-05     No    Positive      1
24  2022-09-05    Yes    Positive      1

In [ ]:
new_df = df[['Timestamp','linked','test_result']].groupby(['Timestamp', 'linked','test_result']).size().reset_index().rename(columns={0:'total'})
new_df[new_df['test_result']=='Positive']
link_df =new_df.pivot_table(index='Timestamp', columns=['linked'], values='total', aggfunc='sum').reset_index()
link_df['total_pos'] = link_df['No'] +link_df['Yes']
link_df

linked   Timestamp  No  Yes  total_pos
0       2022-08-29   4    1          5
1       2022-08-30   4    6         10
2       2022-08-31   1    2          3
3       2022-09-01   4    6         10
4       2022-09-02   2    1          3
5       2022-09-03   2    1          3
6       2022-09-04   6    3          9
7       2022-09-05   2    4          6

In [ ]:
from dateutil import parser
dt = parser.parse(str(pd.to_datetime(df['Timestamp']).min()))
print(dt.year, dt.month, dt.day)

2022 8 29

In [ ]:
df.shape[0]

49

In [ ]:
# df[df['linked']=='Yes'].count()
df['linked'].tolist().count('Yes')

24

In [ ]:
(df['linked'].tolist().count('Yes')/df['test_result'].tolist().count('Positive'))* 100

88.88888888888889

In [ ]:
final_df[['Country','Currency']].groupby(['Country','Currency']).size().reset_index()